name = "spingrannybet-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spingrannybet.cz"
HMAC_KEY = "68f152923824c4d4f44a30692bf2249ae2b9d331a1182ed31354c7555c89f626"
COOKIE_NAME = "z7h"
PLAY_PATH = "discover"
BUTTON_ID = "p508a64a0d51e3854986c617f608720c8"
GATE_SALT = "9e511c9e0d566311"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "kc5o"
CTA_SELECTOR = ".play-button"
